import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright configuration for the specs generated by AI QA Agent.
 *
 * The QA engine drives this file through `npx playwright test`, so anything the engine
 * needs to vary is read from the environment rather than hardcoded here.
 */
const baseURL = process.env["PLAYWRIGHT_BASE_URL"] ?? "http://localhost:8080";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: Boolean(process.env["CI"]),
  retries: process.env["CI"] ? 2 : 0,
  reporter: [["list"], ["html", { open: "never" }]],
  outputDir: "test-results",
  timeout: 30_000,

  use: {
    baseURL,
    // Artifacts the "Test result" screen surfaces when a run fails.
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "off",
  },

  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],

  // Reuses the dev server when one is already listening, and starts one otherwise.
  webServer: {
    command: "npm run dev",
    url: baseURL,
    reuseExistingServer: true,
    timeout: 120_000,
  },
});
