/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as GherkinRouteImport } from './routes/gherkin'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'
import { Route as AutomationTestIdRouteImport } from './routes/automation.$testId'
import { Route as BacklogIndexRouteImport } from './routes/backlog.index'
import { Route as BacklogStoryIdRouteImport } from './routes/backlog.$storyId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdAnalysisRouteImport } from './routes/projects.$projectId.analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const GherkinRoute = GherkinRouteImport.update({
  id: '/gherkin',
  path: '/gherkin',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationTestIdRoute = AutomationTestIdRouteImport.update({
  id: '/automation/$testId',
  path: '/automation/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogIndexRoute = BacklogIndexRouteImport.update({
  id: '/backlog/',
  path: '/backlog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogStoryIdRoute = BacklogStoryIdRouteImport.update({
  id: '/backlog/$storyId',
  path: '/backlog/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdAnalysisRoute =
  ProjectsProjectIdAnalysisRouteImport.update({
    id: '/projects/$projectId/analysis',
    path: '/projects/$projectId/analysis',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/gherkin': typeof GherkinRoute
  '/inventory': typeof InventoryRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/automation/$testId': typeof AutomationTestIdRoute
  '/backlog/$storyId': typeof BacklogStoryIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/automation/': typeof AutomationIndexRoute
  '/backlog/': typeof BacklogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/analysis': typeof ProjectsProjectIdAnalysisRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/gherkin': typeof GherkinRoute
  '/inventory': typeof InventoryRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/automation/$testId': typeof AutomationTestIdRoute
  '/backlog/$storyId': typeof BacklogStoryIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/automation': typeof AutomationIndexRoute
  '/backlog': typeof BacklogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/analysis': typeof ProjectsProjectIdAnalysisRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/gherkin': typeof GherkinRoute
  '/inventory': typeof InventoryRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/automation/$testId': typeof AutomationTestIdRoute
  '/backlog/$storyId': typeof BacklogStoryIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/automation/': typeof AutomationIndexRoute
  '/backlog/': typeof BacklogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/analysis': typeof ProjectsProjectIdAnalysisRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coverage'
    | '/gherkin'
    | '/inventory'
    | '/runs'
    | '/settings'
    | '/automation/$testId'
    | '/backlog/$storyId'
    | '/projects/new'
    | '/automation/'
    | '/backlog/'
    | '/projects/'
    | '/projects/$projectId/analysis'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coverage'
    | '/gherkin'
    | '/inventory'
    | '/runs'
    | '/settings'
    | '/automation/$testId'
    | '/backlog/$storyId'
    | '/projects/new'
    | '/automation'
    | '/backlog'
    | '/projects'
    | '/projects/$projectId/analysis'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/coverage'
    | '/gherkin'
    | '/inventory'
    | '/runs'
    | '/settings'
    | '/automation/$testId'
    | '/backlog/$storyId'
    | '/projects/new'
    | '/automation/'
    | '/backlog/'
    | '/projects/'
    | '/projects/$projectId/analysis'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverageRoute: typeof CoverageRoute
  GherkinRoute: typeof GherkinRoute
  InventoryRoute: typeof InventoryRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  AutomationTestIdRoute: typeof AutomationTestIdRoute
  BacklogStoryIdRoute: typeof BacklogStoryIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
  BacklogIndexRoute: typeof BacklogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdAnalysisRoute: typeof ProjectsProjectIdAnalysisRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gherkin': {
      id: '/gherkin'
      path: '/gherkin'
      fullPath: '/gherkin'
      preLoaderRoute: typeof GherkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/$testId': {
      id: '/automation/$testId'
      path: '/automation/$testId'
      fullPath: '/automation/$testId'
      preLoaderRoute: typeof AutomationTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog/': {
      id: '/backlog/'
      path: '/backlog'
      fullPath: '/backlog/'
      preLoaderRoute: typeof BacklogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog/$storyId': {
      id: '/backlog/$storyId'
      path: '/backlog/$storyId'
      fullPath: '/backlog/$storyId'
      preLoaderRoute: typeof BacklogStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/analysis': {
      id: '/projects/$projectId/analysis'
      path: '/projects/$projectId/analysis'
      fullPath: '/projects/$projectId/analysis'
      preLoaderRoute: typeof ProjectsProjectIdAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverageRoute: CoverageRoute,
  GherkinRoute: GherkinRoute,
  InventoryRoute: InventoryRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  AutomationTestIdRoute: AutomationTestIdRoute,
  BacklogStoryIdRoute: BacklogStoryIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  AutomationIndexRoute: AutomationIndexRoute,
  BacklogIndexRoute: BacklogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdAnalysisRoute: ProjectsProjectIdAnalysisRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
